// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2-3bqPLCqXsx2bumQOwSQIziO4I-hb8',
    appId: '1:371556000831:web:3646d856fdf297b8efc48a',
    messagingSenderId: '371556000831',
    projectId: 'smarthome-7a84a',
    authDomain: 'smarthome-7a84a.firebaseapp.com',
    databaseURL: 'https://smarthome-7a84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-7a84a.appspot.com',
    measurementId: 'G-X561G83593',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPoNkYHQ63UPXhjOkL1lqGcevg2by4q4',
    appId: '1:371556000831:android:083fdb8abdf36ec2efc48a',
    messagingSenderId: '371556000831',
    projectId: 'smarthome-7a84a',
    databaseURL: 'https://smarthome-7a84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-7a84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuyOoYYqaY2ckbiZ-2rRw1MmjyQrnskc',
    appId: '1:371556000831:ios:a4699dc899ddc360efc48a',
    messagingSenderId: '371556000831',
    projectId: 'smarthome-7a84a',
    databaseURL: 'https://smarthome-7a84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-7a84a.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuyOoYYqaY2ckbiZ-2rRw1MmjyQrnskc',
    appId: '1:371556000831:ios:e9bf5518e5ac9e15efc48a',
    messagingSenderId: '371556000831',
    projectId: 'smarthome-7a84a',
    databaseURL: 'https://smarthome-7a84a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-7a84a.appspot.com',
    iosBundleId: 'com.example.smartHome.RunnerTests',
  );
}
